logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

spring:
  mongodb:
    embedded:
      version: 5.0.5
  redis:
    host: localhost
    port: 6379

jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key
